/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "ozstore_constants.h"

namespace ozstore {

const ozstoreConstants g_ozstore_constants;

ozstoreConstants::ozstoreConstants() {
}

} // namespace

