/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ozstore_CONSTANTS_H
#define ozstore_CONSTANTS_H

#include "ozstore_types.h"

namespace ozstore {

class ozstoreConstants {
 public:
  ozstoreConstants();

};

extern const ozstoreConstants g_ozstore_constants;

} // namespace

#endif
