// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "../ozcore/ozone.h"
#include "OZWriteService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>
#include <string>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace std;

using boost::shared_ptr;

using namespace ozstore;

class OZWriteServiceHandler : virtual public OZWriteServiceIf
{
	public:
		OZWriteServiceHandler(const string& path)
		{
			if(ozwrite_open(&ow, path.c_str()))
			{
				throw TException("Open db fail.");
			}
		}

		void put(const std::string& key, const std::string& value)
		{
			//Try put
			int ret = ozwrite_put(&ow, key.c_str(), value.c_str());
			if(!ret)
			{
				return ;
			}
			// Not success
			OZException exp;
			switch(ret)
			{
				case 1:
					exp.why = "invalid handle";
					break;
				case 2:
					exp.why = "write key error";
					break;
				case 3:
					exp.why = "write value error";
					break;
				default:
					exp.why = "unknown error";
					break;
			}
			throw exp;
		}

		void puts(const std::vector<std::string> & key, const std::vector<std::string> & value)
		{
			// Your implementation goes here
			printf("puts\n");
		}

	private:
		OZWrite ow;
};

int main(int argc, char **argv)
{
	int port = 9090;
	string path("/tmp/test_db");
	shared_ptr<OZWriteServiceHandler> handler(new OZWriteServiceHandler(path));
	shared_ptr<TProcessor> processor(new OZWriteServiceProcessor(handler));
	shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
	shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
	shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

	TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
	server.serve();
	return 0;
}

